### ISSUE TITLE
ListButton

### ISSUE THREAD

**Issue by RubenDominguesPires** [PTGUESS/PTGUESS.github.io#1]
Estou a tentar mete-lo na direita mas não consigo.

![Captura de ecrã 2024-02-26 143343](https://github.com/PTGUESS/PTGUESS.github.io/assets/115170459/1192f50d-b62b-4ead-80fd-ac00a9400191)

**Comment by SimaoNevesCurado** [comment]
experimenta criar um div com o width a 100% o height podes escolher tu
dentro desse div colocas isso e tentas coloca-lo á direita.

podes tambem deixar como esta e usar position:absolute mas isso pode te sobrepor algumas coisas, mas experimenta.

**Comment by RubenDominguesPires** [comment]
Resolvido, decidi deixar assim, achei que ficasse melhor :)
![Captura de ecrã 2024-02-26 201817](https://github.com/PTGUESS/PTGUESS.github.io/assets/115170459/a0da082e-bdf6-428a-8414-c44d45a3fc5d)
